apiVersion: apps/v1
kind: Deployment
metadata:
  name: special-offers
spec:
  selector:
    matchLabels:
      app: special-offers
  template:
    metadata:
      labels:
        app: special-offers
    spec:
      containers:
      - name: special-offers
        image: special-offers:1.0.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: special-offers
spec:
  type: LoadBalancer
  selector:
    app: special-offers
  ports:
  - name: special-offers
    port: 5505
    targetPort: 80

