apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty-program
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyalty-program
  template:
    metadata:
      labels:
        app: loyalty-program
    spec:
      containers:
      - name: loyalty-program
        image: loyalty-program:1.0.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: STARTUPDLL
            value: "api/LoyaltyProgram.dll"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: loyalty-program-consumer
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers: 
            - name: loyalty-program
              image: loyalty-program:1.0.1
              imagePullPolicy: IfNotPresent
              env: 
                - name: STARTUPDLL
                  value: "consumer/EventConsumer.dll"
          restartPolicy: Never
  concurrencyPolicy: Forbid

---
apiVersion: v1
kind: Service
metadata:
  name: loyalty-program
spec:
  type: LoadBalancer
  selector:
    app: loyalty-program
  ports:
  - name: loyalty-program
    port: 5000
    targetPort: 80


  


